name = "edin-labs-mcp"
main = "worker.js"
compatibility_date = "2026-04-01"
workers_dev = true

[[kv_namespaces]]
binding = "COPY"
id = "c76f61274a2f4eb59075679e8eb90e0b"

[vars]
SITE_URL = "https://edinlabs.ai"
